# Generated by Django 6.0 on 2026-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_admintransaction_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintransaction',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid by Student'), ('transfer_pending', 'Pending Transfer'), ('transferred', 'Transferred to Teacher')], max_length=20),
        ),
    ]
