# Generated by Django 6.0 on 2026-02-08 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_admintransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withdrawn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.teacherwallet')),
            ],
        ),
    ]
