# Generated by Django 6.0 on 2026-02-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_category_is_deleted'),
        ('wallet', '0004_teacherwallet_teachertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertransaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
