# Generated by Django 6.0 on 2026-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_teachertransaction_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransaction',
            name='razorpay_payout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
