# Generated by Django 6.0 on 2026-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_admintransaction_razorpay_payout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintransaction',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid by Student'), ('transfer_pending', 'Pending Transfer'), ('transferred', 'Transferred to Teacher'), ('payout_processing', 'Payout Processing'), ('payout_failed', 'Payout Failed')], max_length=20),
        ),
    ]
