# Generated by Django 6.0 on 2026-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_admintransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
