# Generated by Django 6.0 on 2026-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_teachertransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertransaction',
            name='source',
            field=models.CharField(choices=[('course_sale', 'Course Sale'), ('live_class', 'Live Class'), ('withdrawal', 'Withdrawal')], default='course_sale', max_length=20),
        ),
    ]
