# Generated by Django 6.0 on 2026-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_teachertransaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintransaction',
            name='source',
            field=models.CharField(choices=[('course_fee', 'Course Fee'), ('live_class', 'Live Class'), ('teacher_withdrawal', 'Teacher Withdrawal'), ('other', 'Other')], max_length=20),
        ),
    ]
