# Generated by Django 6.0 on 2026-02-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0006_alter_liveclass_thumbnail'),
        ('wallet', '0010_alter_admintransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransaction',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_trasactions', to='liveclass.liveclass'),
        ),
    ]
