# Generated by Django 6.0 on 2026-02-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0006_alter_liveclass_thumbnail'),
        ('wallet', '0011_admintransaction_live_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertransaction',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_transactions', to='liveclass.liveclass'),
        ),
    ]
