# Generated by Django 6.0 on 2026-02-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_tag_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
