# Generated by Django 6.0 on 2026-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
