# Generated by Django 6.0 on 2026-02-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0002_alter_liveclass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
