# Generated by Django 6.0 on 2026-02-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0003_liveclass_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
