# Generated by Django 6.0 on 2026-02-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0004_liveclass_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='liveclass_thumbnails/'),
        ),
    ]
