# Generated by Django 6.0 on 2026-02-25 09:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0005_liveclass_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
