# Generated by Django 6.0 on 2026-01-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='postion',
            new_name='position',
        ),
    ]
