# Generated by Django 6.0 on 2026-01-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_postion_lesson_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position']},
        ),
    ]
