# Generated by Django 6.0 on 2026-02-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('blocked', 'Blocked')], default='draft', max_length=10),
        ),
    ]
