# Generated by Django 6.0 on 2026-02-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
