# Generated by Django 6.0 on 2026-02-12 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_orderitem_payment'),
        ('promotions', '0003_coupon_couponserializer_couponsage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couponsage',
            new_name='CouponUsage',
        ),
    ]
