# Generated by Django 6.0 on 2026-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_rename_couponsage_couponusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponSerializer',
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
