# Generated by Django 6.0 on 2026-02-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_delete_couponserializer_coupon_max_uses_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
