# Generated by Django 6.0 on 2026-03-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_alter_coupon_is_active_alter_offer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='max_uses',
        ),
    ]
