# Generated by Django 6.0 on 2026-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_remove_offer_max_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_course_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
