# Generated by Django 6.0 on 2025-12-18 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_type', models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experience')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(help_text='Highesh qualification of the teacher', max_length=255)),
                ('subjects', models.CharField(help_text='Subjects teacher can teach', max_length=255)),
                ('bio', models.TextField(help_text='Short introduction about the teacher')),
                ('years_of_exp', models.PositiveIntegerField(blank=True, help_text='Required only if teacher is experienced', null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='teacher_resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
