# Generated by Django 6.0 on 2025-12-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='years_of_exp',
            new_name='years_of_experience',
        ),
    ]
