# Generated by Django 6.0 on 2026-01-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_rename_years_of_exp_teacherprofile_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/profile_photos/'),
        ),
    ]
