# Generated by Django 6.0 on 2026-01-09 12:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_teacherprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
