# Generated by Django 6.0 on 2026-01-18 19:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0004_remove_teacherprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
