# Generated by Django 6.0 on 2026-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0005_alter_teacherprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
