# Generated by Django 6.0 on 2026-02-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0006_teacherprofile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ifse_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
