# Generated by Django 6.0 on 2026-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0007_teacherprofile_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_type',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('experienced', 'Experience')], max_length=20, null=True),
        ),
    ]
